### ISSUE TITLE
Fibonacci Series

### ISSUE THREAD

**Issue by spirecoder** [spirecoder/learn-kotlin#1]
create a program to print the value of  fibonacci series in both java and kotlin

**Comment by ranjankm** [comment]
> create a program to print fibonacci series in both java and kotlin

Hi,
I would like to contribute to this project.

**Comment by spirecoder** [comment]
> > create a program to print fibonacci series in both java and kotlin
> 
> Hi,
> I would like to contribute to this project.
sure
